#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'rel-vel','console_scripts','rel_vel'
__requires__ = 'rel-vel'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('rel-vel', 'console_scripts', 'rel_vel')()
    )
